#!/bin/bash

echo "#################################################################"
if [[ $EUID -ne 0 ]]; then
echo " ███████ ██████  ██████   ██████  ██████  ██ "
echo " ██      ██   ██ ██   ██ ██    ██ ██   ██ ██ "
echo " █████   ██████  ██████  ██    ██ ██████  ██ "
echo " ██      ██   ██ ██   ██ ██    ██ ██   ██    "
echo " ███████ ██   ██ ██   ██  ██████  ██   ██ ██ "                                                                                        
echo "#################################################################"
echo "Superuser privileges or sudo required to execute the script." 
echo "#################################################################"
exit 1
fi

sudo systemctl daemon-reload

sudo systemctl stop zramsystemd.service

sudo systemctl disable zramsystemd.service

sudo systemctl daemon-reload

sudo systemctl stop zramsystemd.service

sudo systemctl disable zramsystemd.service

sudo swapoff /dev/zram0

sudo modprobe -r zram

sudo echo 1 > /sys/module/zswap/parameters/enabled

clear

echo "#################################################################"
echo " ██████   ██████  ███    ██ ███████ ██ "
echo " ██   ██ ██    ██ ████   ██ ██      ██ "
echo " ██   ██ ██    ██ ██ ██  ██ █████   ██ "
echo " ██   ██ ██    ██ ██  ██ ██ ██         "
echo " ██████   ██████  ██   ████ ███████ ██ "                                                                                                                
echo "#################################################################"
echo "zram-systemd has been successfully stopped."
echo "#################################################################"
echo "To start zram-systemd again, use the command: sudo zram-systemd-start"
echo "#################################################################"  
read -p "To apply the changes, you need to restart system. (y/n): " confirm
                
if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
echo "#################################################################"
echo "Restarting the system..."    
echo "#################################################################"
sudo reboot
else
echo "#################################################################"
echo "Restart canceled."
echo "#################################################################"
fi
