#!/bin/bash

echo "#################################################################"
if [[ $EUID -ne 0 ]]; then
echo " ███████ ██████  ██████   ██████  ██████  ██ "
echo " ██      ██   ██ ██   ██ ██    ██ ██   ██ ██ "
echo " █████   ██████  ██████  ██    ██ ██████  ██ "
echo " ██      ██   ██ ██   ██ ██    ██ ██   ██    "
echo " ███████ ██   ██ ██   ██  ██████  ██   ██ ██ "                                                                                        
echo "#################################################################"
echo "(Superuser privileges or sudo required to execute the script)" 
echo "#################################################################"
exit 1
fi

sudo systemctl daemon-reload

sudo systemctl stop zramsystemd.service

sudo systemctl disable zramsystemd.service

sudo systemctl daemon-reload

sudo systemctl stop zramsystemd.service

sudo systemctl disable zramsystemd.service

sudo swapoff /dev/zram0

sudo modprobe -r zram

sudo echo 1 > /sys/module/zswap/parameters/enabled

sudo rm -rf /etc/systemd/system/zram-systemd

sudo cp /usr/bin/zram-systemd /etc/systemd/system/

sudo chmod +x /etc/systemd/system/zram-systemd

clear

echo "#################################################################"
read -p "Enter the desired size for ZRAM (e.g., 2G or 4G or 8G): " zram_size_input
echo "#################################################################"

if [[ $zram_size_input == *GB ]]; then
echo "#################################################################"
echo "Please enter the size with 'G' in uppercase, for example: 2G or 4G or 8G"
echo "#################################################################"
exit 1
fi

if [[ $zram_size_input == *gb ]]; then
echo "#################################################################"
echo "Please enter the size with 'G' in uppercase, for example: 2G or 4G or 8G"
echo "#################################################################"
exit 1
fi

if [[ $zram_size_input == *g ]]; then
echo "#################################################################"
echo "Please enter the size with 'G' in uppercase, for example: 2G or 4G or 8G"
echo "#################################################################"
exit 1
fi

zram_size="${zram_size_input//G}"
read -p "Choose a compression algorithm (l for lz4, z for zstd): " selected_algorithm
echo "#################################################################"
case $selected_algorithm in
l)
compression_algorithm="lz4"
;;
z)
compression_algorithm="zstd"
;;
*)
echo "Invalid choice. Using the default algorithm (lz4)."
echo "#################################################################"
compression_algorithm="lz4"
;;
esac

read -p "Enter the desired priority for ZRAM (e.g., 100 or 200): " zram_priority
echo "#################################################################"

if [[ $zram_priority == "10%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "20%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "30%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "40%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "50%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "60%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "60%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "70%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "80%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "90%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "100%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "110%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "120%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "130%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "140%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "150%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "160%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "170%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "180%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "190%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "200%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "210%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "220%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "230%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "240%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "250%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "260%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "270%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "280%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "290%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "300%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "310%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "320%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "330%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "340%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "350%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "360%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "300%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "370%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "380%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "390%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "400%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "410%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "420%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "430%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "440%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "450%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "460%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "470%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "480%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "490%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "500%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

if [[ $zram_priority == "%" ]]; then
zram_priority="100"
echo "Automatic priority (100) chosen."
echo "#################################################################"
fi

echo "#!/bin/bash

echo 0 > /sys/module/zswap/parameters/enabled
modprobe zram
zramctl /dev/zram0 --algorithm $compression_algorithm --size ${zram_size}G
mkswap -U clear /dev/zram0
swapon --priority $zram_priority /dev/zram0" > /etc/systemd/system/zram-systemd

clear

sudo systemctl daemon-reload

sudo systemctl enable zramsystemd.service

sudo systemctl start zramsystemd.service

sudo systemctl daemon-reload

sudo systemctl enable zramsystemd.service

sudo systemctl start zramsystemd.service

clear

echo "#################################################################"
echo " ██████   ██████  ███    ██ ███████ ██ "
echo " ██   ██ ██    ██ ████   ██ ██      ██ "
echo " ██   ██ ██    ██ ██ ██  ██ █████   ██ "
echo " ██   ██ ██    ██ ██  ██ ██ ██         "
echo " ██████   ██████  ██   ████ ███████ ██ "                                                                                                                    
echo "#################################################################"
echo "(the zram-systemd configuration has been successfully set)"
echo "#################################################################"
read -p "(To apply the changes, you need to restart system) (y/n) >> " confirm
                
if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
echo "#################################################################"
echo "(Restarting the system)"    
echo "#################################################################"
sudo reboot
else
echo "#################################################################"
echo "(Restart canceled)"
echo "#################################################################"
fi
